# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Palm-Doc
version:      1.14
version_from: Doc.pm
installdirs:  site
requires:
    Palm::PDB:                     1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
